[project]
name = "interview-qa-engineer-develop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "aiohttp>=3.13.3",
    "fastapi[standard]>=0.128.0",
    "psycopg2>=2.9.11",
    "psycopg2-binary>=2.9.11",
    "sqlalchemy>=2.0.46",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-sugar>=1.1.1",
    "pyyaml>=6.0.3",
    "ruff>=0.14.14",
    "testcontainers>=4.14.0",
]
